### ISSUE TITLE
wechat2.xxx  getAuthorizer  bug

### ISSUE THREAD

**Issue by Sgenmi** [easy-swoole/wechat#118]
src/OpenPlatform/Base/Client.php

![image](https://user-images.githubusercontent.com/3337501/113103459-e3554080-9231-11eb-90f9-1d201616b6dc.png)

**Comment by Player626** [comment]
https://github.com/easy-swoole/wechat/pull/119

**Comment by Player626** [comment]
你可以使用`composer require easyswoole/wechat 2.x-dev`
