### ISSUE TITLE
建议将 EasySwoole\WeChat\Kernel\BaseClient 中 getClient 改成  public

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#131]
建议将 EasySwoole\WeChat\Kernel\BaseClient 中 getClient 改成  public。
理由：有的接口SDK中没有集成进去，需要自己去调用，改为 public 后，就可以自由发挥了。例如再集成小程序扫普通二维码打开小程序时，https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/qrcode/qrcodejumpdownload.html

里面二维码规则的添加、修改、删除、发布，没有集成进去，需要自己去调用。

**Comment by Player626** [comment]
目前代码 还没有写到这一块.如果您有时间可以帮忙一起贡献.或者自己去用反射实现呢
