### ISSUE TITLE
第三方平台模式下，根据code获取用户信息请求地址没有做兼容

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#132]
第三方平台模式下，根据code获取用户信息请求地址没有做兼容

第三方平台根据 code 获取用户信息的地址为：https://api.weixin.qq.com/sns/oauth2/component/access_token，
并且请求中应包含 component_appid 与 component_access_token

详见：https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Official_Accounts/official_account_website_authorization.html

**Comment by XueSiLf** [comment]
马上解决
