### ISSUE TITLE
开放平台的消息类型字段，除了 InfoType 还有 MsgType

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#150]
https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/OpenPlatform/Server/Guard.php#L64

此处应该为

`return $this->__isset('InfoType') ? $this->get('InfoType') : $this->get('MsgType');`

**Comment by XueSiLf** [comment]
此问题已修复，详细请看 #157
