### ISSUE TITLE
开放平台代小程序实现业务，没有包含 Account\Client

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#153]
https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/OpenPlatform/Authorizer/MiniProgram/Application.php#L15

应该是遗漏了，没有在这里面加。

**Comment by XueSiLf** [comment]
这个没遗漏，这个是在上层 wechat/src/OpenPlatform/Application.php 进行调用。
