### ISSUE TITLE
发布小程序接口，传惨错误

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#154]
https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/OpenPlatform/Authorizer/MiniProgram/Code/Client.php#L197

按照文档 [发布已通过审核的小程序](https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/api/code/release.html)，需要传参为 `{}`，代码中的传参为 `[]`，会报错误：`data format error`

需修改为：`new Stream('{}')`

**Comment by XueSiLf** [comment]
好的，感谢反馈，这边稍后看看。

**Comment by XueSiLf** [comment]
此问题已修复，详细请看 #157
