### ISSUE TITLE
代小程序实现业务，获取校验文件名称及内容，不传参会报错

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#155]
https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/OpenPlatform/Authorizer/MiniProgram/QrCodeJump/Client.php#L41

不传参时，会报错  44002 `empty post data`
应该加上：`->setBody(new Stream('{}'))`

https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/OpenPlatform/Authorizer/MiniProgram/QrCodeJump/Client.php#L21

获取已设置的二维码规则方法也有同样的错误，是不是因为 POST 类型 body 里面必须传参。

**Comment by XueSiLf** [comment]
好的，感谢反馈，这边稍后看看。

**Comment by XueSiLf** [comment]
此问题已修复，详细请看 #157
