### ISSUE TITLE
根据文档要求，添加模板需要在请求头中加入：content-type: application/json

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#156]
https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/MiniProgram/SubscribeMessage/Client.php#L62

根据微信 [添加模板文档](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.addTemplate.html)，需要在请求头中加入：`content-type: application/json`，否则会报：`200014  missing parameter tid`

https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/MiniProgram/SubscribeMessage/Client.php#L87

删除同样需要加请求头。

**Comment by XueSiLf** [comment]
好的，感谢反馈，这边稍后就修复。

**Comment by XueSiLf** [comment]
此问题已修复 #157
