### ISSUE TITLE
小程序的 Application 里应改为 MiniProgram 下的 Server，否则没有解密的 decryptData 方法

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#158]
https://github.com/easy-swoole/wechat/blob/054113ba462f2cba457ec4dab55f454364213121/src/MiniProgram/Application.php#L9

应该为 `use EasySwoole\WeChat\MiniProgram\Server;`

**Comment by XueSiLf** [comment]
好的，马上修复下。
