### ISSUE TITLE
在发送图文消息时，$this->all() 获取的数据是数组，导致 array_merge 后数据不对

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#159]
https://github.com/easy-swoole/wechat/blob/054113ba462f2cba457ec4dab55f454364213121/src/Kernel/Messages/Message.php#L153

改为 `return XML::build(array_merge(['MsgType' => $this->getType()], $this->toXmlArray(), $appends));` 后兼容。

**Comment by XueSiLf** [comment]
此问题已修复，即将在后续发布新版本，急于使用的话请先使用 composer require easyswoole/wechat "2.x-dev".
