### ISSUE TITLE
CheckFile类函数 msgSecCheck 使用的ApiUrl错误

### ISSUE THREAD

**Issue by wxmatchmen** [easy-swoole/wechat#43]
`$url = ApiUrl::generateURL(ApiUrl::IMG_SEC_CHECK,[
            'ACCESS_TOKEN'  => $token
        ]);`
此处使用的为ApiUrl::IMG_SEC_CHECK，该地址为图片检测地址
应该改为ApiUrl::MSG_SEC_CHECK
`$url = ApiUrl::generateURL(ApiUrl::MSG_SEC_CHECK,[
            'ACCESS_TOKEN'  => $token
        ]);`

**Comment by RunsTp** [comment]
感谢您的反馈，已经修复此问题
