### ISSUE TITLE
微信小程序decryptData方法需完善

### ISSUE THREAD

**Issue by sdgvdvsdf** [easy-swoole/wechat#46]
需修复文件位置：namespace EasySwoole\WeChat\MiniProgram
需修复方法：decryptData（）
问题：此方法有可能解析出来的是空（null） 返回类型应为 : ?array   而不是 ：array。
贴一下微信官方的此方法：
![image](https://user-images.githubusercontent.com/28881955/77977580-a4489280-7332-11ea-927e-169eda765de0.png)

**Comment by RunsTp** [comment]
非常感谢您的反馈，现在当解析失败时会抛出 EncryptorError 异常
