### ISSUE TITLE
微信小程序的订阅消息

### ISSUE THREAD

**Issue by sdgvdvsdf** [easy-swoole/wechat#47]
文档的模板消息微信已用订阅消息取代，麻烦更新组件。
![image](https://user-images.githubusercontent.com/28881955/77977983-76b01900-7333-11ea-9825-20d86ed13965.png)

**Comment by RunsTp** [comment]
#51 修复了此问题，等待wechat 发布版本后，执行composer update 即可使用，如您急需使用可以将composer追踪版本指向 dev-master
