### ISSUE TITLE
news消息无法返回多个item

### ISSUE THREAD

**Issue by ximenhuangguaduo** [easy-swoole/wechat#73]
1. **场景**：公众号被动消息恢复，返回图文(News)类型，push多个item, 但微信消息只返回第一条。 
2. **代码**：
    $news = new News();
   
    $item = new NewsItem();
    $item->setTitle('title:1');
    $item->setDescription('desc:1');
    $item->setPicUrl('https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1473836766,4030812874&fm=26&gp=0.jpg');
    $item->setUrl('https://www.baidu.com');
    $news->push($item);

    $item2 = new NewsItem();
    $item2->setTitle('title:2');
    $item2->setDescription('desc:2');
    $item2->setPicUrl('https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1473836766,4030812874&fm=26&gp=0.jpg');
    $item2->setUrl('https://www.jd.com');
    $news->push($item2);

   return $news;

3.**控制台无报错信息**

**Comment by gaobinzhan** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html#5

请仔细阅读微信公众号文档
